# Generated by Django 2.2.9 on 2020-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
